---
branches:
  only:
  - master

- os: linux
  dist: trusty
  language: python
  python: 3.6
  addons:
    apt:
      packages:
      - python-pip

sudo: required

install:
  - pip install cookiecutter

script:
  - cookiecutter --replay --config-file tests/cookiecutterrc .
  - cd Test_project
  - make run
  - docker exec -it test_project_container pip install -e .
  - docker exec -it test_project_container python -c "import test_project"
