---
branches:
  only:
  - master

os: linux
dist: trusty
language: python
python: 3.6
services:
  - docker

sudo: required

install:
  - pip install -r requirements-dev.txt

script:
  - make run
  - docker exec -it {{cookiecutter.project_name|lower|replace('-', '_')}}_container pip install -e .
  - docker exec -it {{cookiecutter.project_name|lower|replace('-', '_')}}_container python -c "import {{cookiecutter.project_name|lower|replace('-', '_')}}"
  - make clean
